- name: Install git
  win_chocolatey:
    name: git
    state: present

- name: Create Git directory
  ansible.windows.win_file:
    path: C:\git\
    state: directory

- name: Clone Packer Hyper-V Repo
  ansible.windows.win_shell: |
    git clone https://github.com/qman-being/packer-hyperv.git
  args:
    chdir: C:\git\

- name: Install required Packer plugins
  ansible.windows.win_shell: |
    packer init --upgrade config.pkr.hcl
  args:
    chdir: C:\git\packer-hyperv

- name: Clone Packer Hyper-V Repo
  ansible.windows.win_shell: |
    git clone https://qman_being:{{ pat }}@github.com/qman-being/packer-vars.git
  args:
    chdir: C:\git\

- name: Install required Packer plugins
  ansible.windows.win_shell: |
    packer init --upgrade config.pkr.hcl
  args:
    chdir: C:\git\packer-hyperv

- name: Run Packer build
  ansible.windows.win_shell: |
    {{ packer_image }}.ps1
  args:
    chdir: C:\git\packer-hyperv

- name: Remove Git directory
  ansible.windows.win_file:
    path: C:\git
    state: absent
