variables:
- group: packer-hyperv-variables

parameters:
- name: agentPool
  displayName: 'Agent Pool Selection'
  type: string
  default: Self-Hosted
  values:
  - Self-Hosted
  - Oracle-Cloud
- name: nodeSelection
  displayName: 'Ansible Node Selection'
  type: string
  default: host_01
  values:
  - host_01
  - host_02
- name: packerBuildImage
  displayName: Packer Build Image
  default: win2022_dc
  values:
  - ubuntu2204
  - win2022_dc_vagrant
  - win2022_dc
  - win2022_std_vagrant
  - win2022_std
- name: packerTemplate
  displayName: Packer Template
  default: win2022_g2
  values:
    - ubuntu2204_g2
    - win2022_g2_vagrant
    - win2022_g2

trigger:
- none

stages:

- stage: 'packerbuild'
  dependsOn: []
  displayName: 'Packer Build'

  jobs:
    - job: 'packerbuild'
      displayName: 'Packer Build'
      pool: ${{ parameters.agentPool }}

      steps:
      - task: Ansible@0
        displayName: Packer Binary Install
        inputs:
          ansibleInterface: 'agentMachine'
          playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/packer_build.yml'
          inventoriesAgentMachine: 'file'
          inventoryFileOnAgentMachine: '/ansible/inventory/prod/hyper_v.ini'
          args: '--extra-vars "nodes=${{ parameters.nodeSelection }} packer_image=hv_${{ parameters.packerBuildImage }} packer_template=${{ parameters.packerTemplate }} pat=$(pat)"'
          failOnStdErr: false
